### ISSUE TITLE
flatlogcodes does not rebuild automatically

### ISSUE THREAD

**Issue by cjbohlman** [magao-x/MagAOX#10]
Discovered after syncing a fork.

**Comment by jaredmales** [comment]
Need to 
1) move `flatlogs` to the lib directory and add it to `libs_to_build` in the top level Makefile
2) probably use `libs/flatlogs/src/flatlogs` as executable, not bin, so an install step is not needed

**Comment by jaredmales** [comment]
This was fixed in Makefile long ago.

**Comment by cjbohlman** [comment]
Hope you all are doing well, congrats on first light :)

**Comment by jaredmales** [comment]
Hey!  Nice to hear from you.  I didn't even notice that your name was on
that issue.

Thanks!  Let us know if you are back in Tucson and want to visit.
