### ISSUE TITLE
Missing telemetry from smc100ccCtrl (stageadc1, stageadc2, stagepickoff, etc)

### ISSUE THREAD

**Issue by joseph-long** [magao-x/MagAOX#128]
Looking at the `/opt/MagAOX/telem` folder on ICC I don't see telemetry from a subset of the stages and it appears to be the smc100ccCtrl ones

**Comment by jaredmales** [comment]
[6e7d3a0](https://github.com/magao-x/MagAOX/commit/6e7d3a0c57d47a70485c730089d254c95755d548)
