### ISSUE TITLE
ttyIOUtils is throwing an error when device is uplugged during read poll 

### ISSUE THREAD

**Issue by cjbohlman** [magao-x/MagAOX#13]
If a device is unplugged while the ttmTalker application is doing its read poll with MagAOX::tty::ttyWriteRead(), the program corrupts and crashes with:

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 10) > this->size() (which is 0)
0   Aborted

Note: This only happens when the device is unplugged during the read poll. At any other time, code behaves normally.

**Comment by jaredmales** [comment]
What is the value of `swallowEcho` in your call to `ttyWriteRead`?

**Comment by jaredmales** [comment]
Ok, I think what's going on is that the poll has not failed, in that some amount of data was read before the device was unplugged.  So `ttyWriteRead` returns `TTY_E_NOERROR`.

But, it is incomplete.  To handle this case, we need to *always* check that the size of `strRead` is what we expect.  So in `ttmTalker::testConnection`, try adding something like
```
if(ouput.size() != 18) //or whatever the correct size is
{
   return -1;
}
```

**Comment by cjbohlman** [comment]
Added this and can't replicate the problem, so I'm going to assume this fixed it, thanks
