### ISSUE TITLE
Stage position properties need some INDI polish

### ISSUE THREAD

**Issue by joseph-long** [magao-x/MagAOX#33]
e.g.

```
In [6]: c.devices['stagesci1'].properties['position'].elements['target'].step
Out[6]: 0.0
```

**Comment by joseph-long** [comment]
Stage position format string is truncating to integer:

```
"%0.3d");  // units of mm, stage has ~ 1/10 um of precision
```

**Comment by joseph-long** [comment]
Stage position target is not producing a setProperty message, possibly due to ordering of `updateIfChanged`

**Comment by joseph-long** [comment]
0.1 µm is 10^-4 mm so we care about 0.0001 difference -> `%.4f` would be the right format

**Comment by jaredmales** [comment]
The max positions is stage dependent, and determined by `zaberLowLevel` when talking to the stage.  This is reported to `zaberCtrl` for it's stage via INDI.  So we need to add an update to the INDI properties for the max value in the callback: https://github.com/magao-x/MagAOX/blob/826f1bf39f13a5963132663edd56e8a2c20f9c10/apps/zaberCtrl/zaberCtrl.hpp#L498

**Comment by joseph-long** [comment]
I think it's trickier than that, if you want to be sure you get the updated limits. You'd have to fire a delProperty and then a defProperty, or even better wait until the zaberLowLevel device is available before sending defProperty messages...

**Comment by jaredmales** [comment]
I was expecting such problems, which is why I didn't implement it already.  The best way to handle it then is in stageCtrl config files, e.g. stagesci1.conf has its `stage.maxPos` set.  Not too big a deal, it requires using a TTY session to set the max in ROM on the stage.

**Comment by jaredmales** [comment]
440013a
