### ISSUE TITLE
Update RTC BIOS

### ISSUE THREAD

**Issue by joseph-long** [magao-x/MagAOX#40]
The other USB ports became usable on ICC (and there's probably other good reasons to update). Will involve more careful recording of the existing state than the ICC state.

**Comment by jaredmales** [comment]
The settings needed are well understood to get to the current level of stability for the PCIe system.  Main risk is that this will make PCIe expansion less stable.  It might help with that too!

I think the main thing to be sure we know is the current BIOS, and that we have that downloaded so we can revert.

**Comment by joseph-long** [comment]
```
[jlong@exao2 ~]$ dmesg | grep -i asus
[    0.000000] DMI: ASUSTeK COMPUTER INC. Z10PE-D8 WS/Z10PE-D8 WS, BIOS 3407 03/10/2017
```

For downloads: https://www.asus.com/us/Motherboards/Z10PED8_WS/HelpDesk_BIOS/

**Comment by joseph-long** [comment]
Applied to AOC workstation today.

**Comment by joseph-long** [comment]
Applied to RTC today. Had to disconnect PCIe expansion cables from the card before I could get in to BIOS and apply the tweaks from `computer_setup.md`
