### ISSUE TITLE
Upgrade to CUDA 11

### ISSUE THREAD

**Issue by joseph-long** [magao-x/MagAOX#42]
- [ ] Install in-situ on RTC...
- [ ] ... ICC ...
- [ ] ... AOC
- [ ] Update https://github.com/magao-x/MagAOX/blob/master/setup/steps/install_cuda.sh#L23-L25

**Comment by jaredmales** [comment]
RTC upgraded.  Download link: wget http://developer.download.nvidia.com/compute/cuda/11.0.1/local_installers/cuda_11.0.1_450.36.06_linux.run

Testing i/p

**Comment by joseph-long** [comment]
Per https://bitbucket.org/icl/magma/issues/25/error-cusparsesolveanalysisinfo_t-does-not CUDA 11 compatibility in MAGMA is coming.
