### ISSUE TITLE
cfitsio error when installing cacao

### ISSUE THREAD

**Issue by bohan-li** [magao-x/MagAOX#47]
When I ran `bash setup/steps/install_cacao.sh`, I got the following error:

```
Found OpenMP
COMPILE_OPTIONS:  
====================================================
VERSION  0.1.03
====================================================
PROJECT_SOURCE_DIR       = /home/bohanli/MagAOX-2019.11.25/cacao
PROJECT_BINARY_DIR       = /home/bohanli/MagAOX-2019.11.25/cacao/_build
USE_CUDA                 = OFF
USE_MAGMA                = OFF
USE QDWHPARTIAL          = 
EXTRAMODULES             = 
====================================================
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Checking for module 'cfitsio'
--   No package 'cfitsio' found
CMake Error at /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GSL (missing: GSL_INCLUDE_DIR GSL_LIBRARY GSL_CBLAS_LIBRARY)
  (found version "")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.12/Modules/FindGSL.cmake:148 (find_package_handle_standard_args)
  src/CommandLineInterface/CMakeLists.txt:17 (find_package)


-- Configuring incomplete, errors occurred!
```

I did a `ls /usr/lib64/ | grep cfitsio` and saw
```
libcfitsio.so.2
libcfitsio.so.2.3.37
```

I also tried adding /usr/lib64 to my LD_LIBRARY_PATH, but the same error occurred. Is there some configuration I'm missing here?

**Comment by joseph-long** [comment]
Fair warning: If you’re not working on a machine set up to be part of MagAO-X or its cousins, the setup scripts will be more of a guide than a fully automated process.

If you’d like a fully automated setup, the remote operation VM described in the handbook will run through the setup scripts in an environment (os version, distribution, etc) that is tested to work. It may be worth doing that anyway, so you can inspect the final state to see what is different.

Taking a wild guess here, you may need to find the cfitsio pkgconfig file, named something like cfitsio.pc, and put it on the pkg-config path.

**Comment by jaredmales** [comment]
It appears that the actual error is from GSL, not cfitsio.  Though we'll need to get cfitsio properly installed, I would start with "sudo apt install libgsl-dev" and see if you get past this.

**Comment by jaredmales** [comment]
or if you are on CentOS run the install_centos7_packages.sh script
