### ISSUE TITLE
Configure AOC NFS timeout

### ISSUE THREAD

**Issue by joseph-long** [magao-x/MagAOX#48]
If CentOS 7.8 has these options we should use them since we're doing r/o NFS anyway 

https://serverfault.com/questions/889860/how-to-configure-reasonable-timeout-for-nfs

**Comment by jaredmales** [comment]
@joseph-long ?

**Comment by joseph-long** [comment]
Well, I guess we didn't really notice problems with NFS for the last couple of years, or I would have gotten around to this sooner...

Done on all three machines. Also fixed up the NAS share name on RTC and ICC while I was at it.
